version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pubquiz
      MYSQL_DATABASE: pubquiz
      MYSQL_USER: pubquiz
      MYSQL_PASSWORD: pubquiz
    ports:
      - "33306:3306"
